### ISSUE TITLE
Importing scramp fails from 1.4.2 onwards

### ISSUE THREAD

**Issue by gerbenoostra** [tlocke/scramp#14]
In a python 3.8 lambda function, when importing `scramp` it fails due to an importerror. Downgrading to 1.4.1 resolves it.
The cause seems to be [here](https://github.com/tlocke/scramp/blob/2de50183a1ddea6b9fdaa5cdff7236c318c6cc26/scramp/__init__.py#L10):
```
try:
    from importlib.metadata import version
except ImportError:
    from importlib_metadata import version
```
As in version 1.4.1 that part is different

**Comment by tlocke** [comment]
Hi @gerbenoostra, could you post a stack trace of the error please? Also, does the Python that you're using come with [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html#module-importlib.metadata) ? If not then you'd need to install the `importlib_metadata` package.

**Comment by gerbenoostra** [comment]
I only got a logentry Unable to import module 'handler': scramp. Couldn't
reproduce the issue locally, it only happened in the lambda.

I guess it doesn't have it, as it is quite a minimal image. I'll try again
with that extra dependency after the weekend.

**Comment by tlocke** [comment]
Another thought: I think Lambda supports Python 3.10, so might be worth upgrading to that and seeing if that supports importlib.metadata.
