### ISSUE TITLE
Can you add new topics in this repository?

### ISSUE THREAD

**Issue by Neustradamus** [tlocke/scramp#7]
@tlocke: I wish you a Happy New Year!

Can you add new topics in this repository like others?
- scram-sha-512
- scram-sha-512-plus
- scram-sha3-512
- scram-sha3-512-plus

Thanks in advance.

**Comment by tlocke** [comment]
Happy New Year @Neustradamus ! I've added in those topics now.

**Comment by Neustradamus** [comment]
@tlocke: Thanks for your wishes and thanks for the adding :)
