### ISSUE TITLE
Can you add reference to RFCs/I-Ds in the README?

### ISSUE THREAD

**Issue by Neustradamus** [tlocke/scramp#8]
@tlocke: I wish you a Happy New Year!

Can you add reference to RFCs/I-Ds in the README?
- https://tools.ietf.org/html/rfc5056
- https://tools.ietf.org/html/rfc5929
- https://datatracker.ietf.org/doc/html/draft-melnikov-scram-sha-512
- https://datatracker.ietf.org/doc/html/draft-melnikov-scram-sha3-512
- https://tools.ietf.org/html/rfc9266

Thanks in advance.

**Comment by ogrebgr** [comment]
I am afraid that the only applicable RFC is 5802

**Comment by Neustradamus** [comment]
RFC 5802 is only for SCRAM-SHA-1(-PLUS) ^^

Current in the README:
```
A Python implementation of the SCRAM authentication protocol defined by RFC 5802 and RFC 7677. Scramp supports the following mechanisms:
- SCRAM-SHA-1
- SCRAM-SHA-1-PLUS
- SCRAM-SHA-256
- SCRAM-SHA-256-PLUS
- SCRAM-SHA-512
- SCRAM-SHA-512-PLUS
- SCRAM-SHA3-512
- SCRAM-SHA3-512-PLUS
```

**Comment by ogrebgr** [comment]
Plus variants are not supported. Channel binding is not supported too. As far as I see it 5802 is the general description of the SCRAM-SASL, not just SHA-1 (and it is the only one supported)

**Comment by Neustradamus** [comment]
We are not in the good ticket :D
Please remove your comments here, I will do same!

**Comment by tlocke** [comment]
I've put these in a new section in the README https://github.com/tlocke/scramp#standards

Scramp doesn't yet support the tls-exported channel binding, but I've added an issue for it at https://github.com/tlocke/scramp/issues/9

**Comment by Neustradamus** [comment]
@tlocke: Thanks for your improvements :)

Attention, at the top:
"A Python implementation of the SCRAM authentication protocol."
-> There is the link to RFC5802, maybe good to link to https://github.com/tlocke/scramp#standards?

You can remove "Scramp supports the following mechanisms: and all protocols" which are now in https://github.com/tlocke/scramp#standards too :)

And the last point, you can put all links:
- https://datatracker.ietf.org/doc/html/***
or
- https://tools.ietf.org/html/***

**Comment by tlocke** [comment]
You're probably right, but maybe the page is good enough for the moment? I'm sure there will be further developments.
